# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51535385f57f7c29512d88bc48bb6b590db9d767c5e7dda3f1b46eb796229f5eb9b47763263f2faba7423ec279727728d203817a7b40306109b8c969f874da2a

test:
  secret_key_base: ad8c0b9b590ebed6f6f934a8b8d44c2328e08c7b472c2a56ff8e715600772c7c5c64f57afd395affac76c1ef3144e596ba46c6b9287762a483fe9dc6113d5f2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
